import { expect, test } from '@playwright/test';

test('same-thread account sources keep configs and frozen jobs distinct; sender, cancel and legacy guards remain visible', async ({ page, request }) => {
  const fixture = await (await request.post('/__fixture/ai-seed')).json();
  const state = () => request.get(`/__fixture/ai-state/${fixture.orgId}`).then(response => response.json());
  await page.goto('/login');
  await page.getByLabel('Email', { exact: true }).fill(fixture.email);
  await page.getByLabel('Mật khẩu', { exact: true }).fill(fixture.password);
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click();
  await expect(page).toHaveURL('/');
  await page.goto('/ai-reports');
  await page.getByRole('tab', { name: /Cấu Hình Tự Động/ }).click();
  const alphaRow = page.getByRole('row').filter({ hasText: 'Account Alpha' });
  const betaRow = page.getByRole('row').filter({ hasText: 'Account Beta' });
  await expect(alphaRow.locator('input[type=text]')).toHaveValue('Prompt Alpha');
  await expect(betaRow.locator('input[type=text]')).toHaveValue('Prompt Beta');
  await alphaRow.getByRole('button', { name: 'Sửa', exact: true }).click();
  await page.getByLabel('Yêu cầu trọng tâm cho AI (Custom Prompt)', { exact: true }).fill('Edited Alpha only');
  const configResponse = page.waitForResponse(response => response.url().includes('/ai-reports/configs/') && response.request().method() === 'PUT');
  await page.getByRole('button', { name: 'Lưu thay đổi', exact: true }).click();
  expect((await configResponse).ok()).toBe(true);
  const configs = (await state()).configs;
  expect(configs.find((config: any) => config.zaloAccountId === fixture.targets[0].zaloAccountId).customPrompt).toBe('Edited Alpha only');
  expect(configs.find((config: any) => config.zaloAccountId === fixture.targets[1].zaloAccountId).customPrompt).toBe('Prompt Beta');
  await page.getByRole('tab', { name: /Tạo Báo Cáo/ }).click();
  await page.getByRole('button', { name: 'Tất cả', exact: true }).click();
  await expect(page.getByText('Nhóm Zalo theo dõi (2/2):', { exact: true })).toBeVisible();
  const generate = page.getByRole('button', { name: /Tạo Báo Cáo Ngay/ });
  await expect(generate).toBeDisabled();
  // Selection uses the explicit sender, while the two source pairs remain separate.
  await page.getByLabel('Tài khoản Zalo gửi báo cáo', { exact: true }).first().press('Enter');
  await page.getByRole('option', { name: /Account Alpha/ }).click();
  await expect(generate).toBeEnabled();
  const submitted = page.waitForResponse(response => response.url().endsWith('/ai-reports/generate') && response.request().method() === 'POST');
  await generate.click();
  const response = await submitted;
  expect(response.status(), await response.text()).toBe(202);
  const dto = response.request().postDataJSON();
  expect(dto.group_targets).toHaveLength(2);
  expect(dto.group_targets).toEqual(expect.arrayContaining(fixture.targets.map((target: any) => ({ zalo_account_id: target.zaloAccountId, group_thread_id: target.groupThreadId }))));
  expect(dto.zalo_account_id).toBe(fixture.targets[0].zaloAccountId);
  const jobId = (await response.json()).jobId;
  await expect.poll(async () => (await state()).jobs.length).toBe(1);
  const persisted = (await state()).jobs[0];
  expect(persisted.id).toBe(jobId);
  expect(persisted.requestData.targets).toEqual(expect.arrayContaining(fixture.targets));
  expect(persisted.requestData.targets).toHaveLength(2);
  expect(persisted.requestData.senderAccountId).toBe(fixture.targets[0].zaloAccountId);
  const polled = page.waitForResponse(response => response.url().endsWith(`/ai-reports/jobs/${jobId}`));
  await polled;
  await page.getByRole('button', { name: 'Hủy tạo báo cáo', exact: true }).click();
  await expect.poll(async () => (await state()).jobs[0].status).toBe('cancelled');
  await expect(page.getByText(/Đã hủy tạo báo cáo/).first()).toBeVisible();
  await page.getByRole('tab', { name: /Lịch Sử Báo Cáo/ }).click();
  const legacyRow = page.getByRole('row').filter({ hasText: 'Legacy browser report' });
  await expect(legacyRow.getByText('Nguồn chưa xác minh', { exact: true })).toBeVisible();
  await expect(legacyRow.getByRole('button', { name: 'Gửi lại báo cáo', exact: true })).toBeDisabled();
});
